{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vpro-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: argocd.salmancloud.xyz   # Tera DNS naam
    http:
      paths:
      - path: /
        pathType: Prefix           # YE LINE MANDATORY HAI 1.30 MEIN
        backend:
          service:
            name: vproapp-service  # Purana 'serviceName' hatake 'service -> name'
            port:
              number: 8080         # Purana 'servicePort' hatake 'port -> number'
{{- end }}
