apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.appSecret.name }}
type: Opaque
data:
  db-pass: {{ .Values.secrets.appSecret.dbPassword }}
  rmq-pass: {{ .Values.secrets.appSecret.rmqPassword }}
