apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  ports:
  - port: {{ .Values.app.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.app.containerPort }}
  selector:
    app: {{ .Values.app.name }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}
spec:
  ports:
  - port: {{ .Values.db.servicePort }}
    targetPort: db-port
    protocol: TCP
  selector:
    app: {{ .Values.db.name }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: vpromc
spec:
  ports:
  - port: {{ .Values.memcached.servicePort }}
    targetPort: mc-port
    protocol: TCP
  selector:
    app: {{ .Values.memcached.name }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbitmq.name }}
spec:
  ports:
  - port: {{ .Values.rabbitmq.servicePort }}
    targetPort: rmq-port
    protocol: TCP
  selector:
    app: {{ .Values.rabbitmq.name }}
  type: ClusterIP
